= My script
Hello, this is my presentation video for my premiers coding competition submision.
This submission is in the grade 9-10 category for educating queenslanders on privacy and safety.
My project is on a topic I am passionate about and truly believe in as a cause: decentralisation. My project has a couple of pages to explain why I think it is important, and optional extra pages for both somewhat technical and simple explanations of mesh routing, mesh networks, and my specific routing method. I hope that this can inform people or spark interest even if I don't do well from a competitive sense.



Imagine you want to send a letter to a friend that contains the super top secret solution to 1+1, an unsolved math problem you have worked hard on for years. You go to the post office, then go home, waiting for your friend's response. Suddenly, you see online that an exact copy of your letter has been leaked! You check the news, and the post office has been broken into. How do you avoid that?

This is a centralised situation, where your letter is given to a middleman, copied, and sent to your friend. To avoid this, you remove the center. You walk to your friends house, drop off the letter, and they put it in a big underground vault filled with gold bars. Noone has a copy of your letter except your friend.

You are a child, struggling with mental health issues. You talk to a peer through discord, and communicate your struggles. Suddenly, you get a random friend request. Sure, why not. You accept it and start talking. This person understands you so well somehow, sympathises with you perfectly, and is addicting to talk to. What you missed is that someone has gained access to discord message logs, and after trawling through chats, found a vulnerable young person who can be taken advantage of. How do you avoid that?

This is a centralised situation, where your messages are given to a middleman, copied, and sent to your friend. To avoid this, you remove the center. You send a message directly to your friend over HaLow radio, and they keep it cryptographically locked in their computer. Noone has a copy of your message except your friend.

Privacy is incredibly important as an issue, for obvious reasons. That scenario could go almost *anywhere*. You could be blackmailed over personal information. They might have gotten access to a home address you sent to your friend. They might know exactly what would hurt you the most, and push you to a mental breaking point. One single center has to be broken for this scenario to play out tens or hundreds of thousands of times.

You and your friends are holding a vote for what pizza to have for dinner. You have a friend named John Votecounter who counts the votes, and everyone sends in their vote to them. One of your friends thinks pineapple doesn't go on pizza, and if they hear you voted for hawaiian pizza, they are going to recite a terribly long boring poem about why pineapple on pizza should be made illegal. Obviously pineapple does go on pizza, so you vote for hawaiian pizza. John Votecounter accidentally tells someone you voted for hawaiian, and it reaches your friend who hates pineapple on pizza. You spend your time during the laborious poem reading thinking about where you went wrong. There was no centralised authority, so shouldn't the privacy problem be solved?

This is a situation where anonymity is important. Decentralisation doesn't automatically mean anonymous, so your pizza voting group must find a way to achieve anonymity. If John Votecounter doesn't know who voted for what, then he doesn't have any secret votes to leak. Eventually you settle on a system that hides who sent what, and noone can leak who said what.

You go back to talking to your friend on a decentralised social media platform. You post, you talk, repeat. Your chats are safe, there is no problem there. So you keep going. You share your life on social media, safe with the knowledge that there is no central server to take out. You send photos, you talk about your school, you shout your secrets into the tangle of threads that make up this platform. One day, a SWAT team shows up at your door, bangs it down, and starts searching. They have guns. They yell, they shout, and they tie you and your family up and interrogate you. How could this possibly happen? With no centralised authority, shouldn't privacy be solved?

This is a situation where anonymity is important. Decentralisation doesn't automatically mean anonymous, so you must find a way to achieve anonymity. If noone can link your profile to your person, then they don't have a person to attack. Eventually, you find a new platform that is decentralised, wipes image EXIF data automatically, uses mesh routing to make it impossible to track you, and you learn how to stay anonymous online.

Mesh networks are incredibly important to modern privacy. I believe that decentralisation and anonymity are two of the most ignored pillars of online safety that exist, which is why I built this. The main centerpeice of my submission revolves around my contribution to developing decentralised routing technology. Although it is unusual, and it doesn't fit an exact use case yet, I enjoyed researching and building it, and I think it makes a good submission to this competition. Along with coincidentally being easier to visualise than many other mesh routing algorithms, it uses technology that I also believe is shaping the future of privacy.